on: [push]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
        example: [src]
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: "recursive"
    - name: Set up Python
      uses: actions/setup-python@v2
      with: 
        python-version: "3.9"
    - name: Install PlatformIO
      run: |
        pip install -U https://github.com/platformio/platformio/archive/develop.zip
        pio pkg install --global --platform symlink://.
    - name: Run PlatformIO
      run: pio ci --board nucleo_f446re
      env: 
        PLATFORMIO_CI_SRC: ${{ matrix.example }}