on: [push]

jobs:
  test:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: "recursive"
    - name: Set up Python
      uses: actions/setup-python@v2
      with: 
        python-version: "3.9"
    - name: Install udev rules
      run: |
        curl -fsSL https://raw.githubusercontent.com/platformio/platformio-core/master/scripts/99-platformio-udev.rules | sudo tee /etc/udev/rules.d/99-platformio-udev.rules
        sudo cp 99-platformio-udev.rules /etc/udev/rules.d/99-platformio-udev.rules]
        sudo service udev restart
    - name: Install PlatformIO
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade platformio
    - name: Run tests on the native platform
      run: pio test -vvv -e nucleo_f446re